### ISSUE TITLE
master-config showコマンドでエラー

### ISSUE THREAD

**Issue by elecdeer** [elecdeer/yosuga-bot#127]
embedsの数が多すぎる？

```
 [2022-03-11T15:08:31.156] [ERROR] command - DiscordAPIError: Invalid Form Body
node-yosuga            | data.embeds: Must be 10 or fewer in length.
node-yosuga            |     at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
node-yosuga            |     at runMicrotasks (<anonymous>)
node-yosuga            |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
node-yosuga            |     at async RequestHandler.push (/app/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
node-yosuga            |     at async CommandInteraction.reply (/app/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:99:5) {
node-yosuga            |   method: 'post',
node-yosuga            |   path: '/interactions/951859051212439563/aW50ZXJhY3Rpb246OTUxODU5MDUxMjEyNDM5NTYzOmVYUjBwM1FwSndhMVlSc0hSTmlUMXprRUtqamVxcmFXZVVxZFdOeDBLN2hlTG5DdldXcWljQzlEZkJDbFNUY2lZZERHZ3FUdGhjOHI3WWlWSktDYW9SNk13T0VVZktxR1Zpd3llUGxZSXpMYUlkcldvMlJJVXJ6YTg3eHI2dXcw/callback',
node-yosuga            |   code: 50035,
node-yosuga            |   httpStatus: 400,
node-yosuga            |   requestData: { json: { type: 4, data: [Object] }, files: [] }
node-yosuga            | }
```

**Comment by elecdeer** [comment]
Interactionへの応答では、普通のメッセージ送信とは埋め込みの上限数が違う
25個までOKだと思っていたんだけど、10個までだったみたい
https://discord.com/developers/docs/resources/channel#embed-object-embed-limits
https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-response-object-messages

**Comment by elecdeer** [comment]
fixed
